import type { Metadata } from "next";
import "./css/style.css"
import Header1 from "./Header/header";
import Footer1 from "./Footer/footer";
import ProductCards from "./MainLP/page";

export const metadata: Metadata = {
  title: "Perifericos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <Header1 />
      <ProductCards />
      <Footer1 />
    </html>
  );
}
